def suma(num1, num2):
    try:
        print(num1 + num2)
    except:
        print("Error inesperado")